kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

pipeline:
  build:
    image: python:3.5.2
    environment:
      # I use dj_database_url to specify my DB settings
      - DATABASE_URL=postgres://postgres@localhost
    commands:
      - sleep 5 # (probably not necessary)
      - pip3 install -r requirements.txt
      - cd projectDir
      - python ./manage.py test
      - cd ..
    when:
      branch: [master]
      event: [push, pull_request] # trigger step on push and pull events
services:
  database:
    image: postgres
    environment:
      - DATABASE_URL=postgres://postgres@localhost
