version: '3'

services:

  database:
    image: postgres
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/convertany
    ports:
      - "80:8000"
    depends_on:
      - database
