version: "3"

services:
  database:
    image: postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/convertany
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - database
